/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solution
 *  Copyright 2021 Riya Singh
 */
@startuml
class items
{
    -description: SimpleStringProperty
    -status: SimpleStringProperty
    -date: SimpleStringProperty

    +setDate(LocalDate dt)
    +getDate()
    +setDescription(String description)
    +getDescription()
    +setStatus(String newStatus)
    +getStatus()
}
@enduml